version: "3.9"
services:
  

  api:
    build:
      context: . 
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgres://postgres:123456@192.168.1.83:5432/simplebank?sslmode=disable


#postgres:
#  image: postgres:12-alpine
#  environment: 
#    - POSTGRES_USER=root
#    - POSTGRES_PASSWORD=secret
#    - POSTGRES_DB=???